ARDUINO_DIR   = /usr/share/arduino
ARDMK_TOOLS   = /usr/share/arduino
AVR_TOOLS_DIR = /usr

ARDUINO_LIBS  =
BOARD_TAG     = nano328
MONITOR_PORT  = /dev/ttyUSB0

include /usr/share/arduino/Arduino.mk
